# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0005_auto_20171202_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='garbage_pic',
            field=models.ImageField(default=' ', upload_to='/home/sinwar/rajhack/cleanraj/sni/site_media/media/things/'),
        ),
    ]
