# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-02 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0006_location_garbage_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='garbage_pic',
            field=models.TextField(blank=True),
        ),
    ]
