# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sni', '0007_auto_20171202_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addthing',
            name='owner',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=' ', upload_to='/home/sinwar/cleanraj-hasura/microservices/app/app/src/cleanraj/sni/site_media/media'),
        ),
        migrations.DeleteModel(
            name='addThing',
        ),
    ]
